# Generated by Django 5.2.5 on 2025-09-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_category_price_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
